### PR TITLE
Test Contribution Proposal

### PR DESCRIPTION
**Pull request by ranms25**
Hey @Irish-C ! 
 This PR was sent as part of OSDC  taught by: @szabgab
I wanted to share my test contributions with you for the project. I believe adding these tests would be beneficial for a few reasons:
Better coverage: These tests cover different parts of the project, ensuring that we test all the important aspects.
Improved reliability: By running these tests, we can verify that the project's functionalities are working as expected, which increases overall reliability.
Preventing regressions: Tests act as a safety net, making sure that any future changes or updates won't break existing functionalities.
Code quality: These tests are well-written and can serve as examples for how to use different parts of the code. They also contribute to the overall code quality of the project.

I hope you find these tests valuable and consider adding them to the project. 
Thanks

Ran

### CODE REVIEW

**Comment by szabgab** [comment]
I recommend you also add a configuration file to enable GitHub Actions to run these tests on every push and on every pull-request.

**Comment by Irish-C** [comment]
> ### Test Contribution Proposal #2
> Hey @Irish-C ! 
>This PR was sent as part of OSDC taught by: @szabgab 
>I wanted to share my test contributions with you for the project. I believe adding these tests would be beneficial for a few reasons: 
>Better coverage: These tests cover different parts of the project, ensuring that we test all the important aspects. 
>Improved reliability: By running these tests, we can verify that the project's functionalities are working as expected, which increases overall reliability. 
>Preventing regressions: Tests act as a safety net, making sure that any future changes or updates won't break existing functionalities. 
>Code quality: These tests are well-written and can serve as examples for how to use different parts of the code. They also contribute to the overall code quality of the project.
> 
> I hope you find these tests valuable and consider adding them to the project. 
>Thanks
> 
> Ran
>


Hi @ranms25 !

I highly appreciate your test contribution. It was indeed well-written and incredibly demonstrates all the benefits you've mentioned. I was able to understand them despite no prior knowledge. Withal, I am glad to consider adding them to my project. 

I would also try to notify my professor of your inputs to ensure they are well-informed. If you don't mind, may I ask if there's a particular merge option you have in mind, anything?

Many thanks,
Irish C.

**Comment by ranms25** [comment]
> 

Hi @Irish-C, thank you 😊 I'm glad it will help, I'm not sure I fully understood your intent, but if you mean what kind of merge to perform, I think it should be performed "squash and merge".

**Comment by Irish-C** [comment]
I'm sorry for the mislead and thank you @ranms25 for your suggestion. I shall close this now. Take care until then!

**Pull request merged**
